
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kosta
 */
public class MyFrame extends javax.swing.JFrame {

    Image image;
    static BufferedImage imageRezerev;
    static Dimension d;
    static Dimension dScrollPanel;
    Points pointsOriginal = new Points();
    Points pointsTransform = new Points();
    Graphics g1;
    Graphics g2;
    static String fileName = "cip1.jpg";

    static {
        try {
            imageRezerev = ImageIO.read(new File(fileName));
            d = new Dimension(imageRezerev.getWidth(null), imageRezerev.getHeight(null));
        } catch (IOException ex) {
            Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form MyFrame
     */
    public MyFrame() {
        initComponents();
        this.g1 = imageJPanel1.getGraphics();
        this.g2 = imageJPanel2.getGraphics();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        imageJPanel1 = new ImageJPanel(fileName);
        jButtonTransform = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        BufferedImage whiteBI = new BufferedImage(d.width, d.height, BufferedImage.TYPE_INT_RGB);
        Graphics whiteG = whiteBI.createGraphics();
        whiteG.setColor(Color.WHITE);
        whiteG.fillRect(0, 0, d.width, d.height);
        imageJPanel2 = new ImageJPanel(whiteBI, d);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dScrollPanel = new Dimension(jScrollPane1.getWidth(),jScrollPane1.getHeight());
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(581, 718));

        imageJPanel1.setSize(d);
        imageJPanel1.setBackground(new java.awt.Color(255, 255, 204));
        imageJPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imageJPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout imageJPanel1Layout = new javax.swing.GroupLayout(imageJPanel1);
        imageJPanel1.setLayout(imageJPanel1Layout);
        imageJPanel1Layout.setHorizontalGroup(
            imageJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        imageJPanel1Layout.setVerticalGroup(
            imageJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(imageJPanel1);

        jButtonTransform.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jButtonTransform.setText("Transform");
        jButtonTransform.setPreferredSize(new java.awt.Dimension(165, 25));
        jButtonTransform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransformActionPerformed(evt);
            }
        });

        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(581, 718));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(581, 718));

        imageJPanel2.setBackground(new java.awt.Color(255, 255, 255));
        imageJPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imageJPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout imageJPanel2Layout = new javax.swing.GroupLayout(imageJPanel2);
        imageJPanel2.setLayout(imageJPanel2Layout);
        imageJPanel2Layout.setHorizontalGroup(
            imageJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        imageJPanel2Layout.setVerticalGroup(
            imageJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(imageJPanel2);

        jLabel1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel1.setText("ORIGINAL IMAGE:");

        jLabel2.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel2.setText("TRANSFORMED IMAGE:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTransform, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonTransform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTransformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransformActionPerformed
        System.out.println("ButtonTransform pressed");


        Transformation transformation = new Transformation(imageRezerev);
        Matrix matrix = new Matrix(pointsOriginal,pointsTransform);
        transformation.Transform(matrix);

        BufferedImage bufferedImage = transformation.Transform(matrix);




        pointsTransform.Draw(bufferedImage.getGraphics());
        imageJPanel2.setImage(bufferedImage);
        jScrollPane2.updateUI();
    }//GEN-LAST:event_jButtonTransformActionPerformed

    private void imageJPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageJPanel1MousePressed

        if (pointsOriginal.getPointsSize() > 2) {
            clear(imageJPanel1);
        }
        pointsOriginal.add(new Point(evt.getX(), evt.getY()));

        BufferedImage newImage = new BufferedImage(imageRezerev.getWidth(null), imageRezerev.getHeight(null), BufferedImage.TYPE_INT_RGB);
        Graphics gr = newImage.createGraphics();
        gr.drawImage(imageRezerev, 0, 0, null);
        pointsOriginal.Draw(newImage.getGraphics());
        imageJPanel1.setImage(newImage);
        jScrollPane1.updateUI();
    }//GEN-LAST:event_imageJPanel1MousePressed

    private void imageJPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageJPanel2MousePressed
        if (pointsTransform.getPointsSize() > 2) {
            clear(imageJPanel1);
        }
        pointsTransform.add(new Point(evt.getX(), evt.getY()));

        BufferedImage newImage = new BufferedImage(d.width, d.height, BufferedImage.TYPE_INT_ARGB);
        Graphics gr = newImage.createGraphics();
        gr.fillRect(0, 0, d.width, d.height);
        pointsTransform.Draw(newImage.getGraphics());
        imageJPanel2.setImage(newImage);
        jScrollPane2.updateUI();
    }//GEN-LAST:event_imageJPanel2MousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setDefaltPoints();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public void clear(ImageJPanel jPanel) {
        jPanel.paintComponents(jPanel.getGraphics());
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        } catch (InstantiationException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        } catch (IllegalAccessException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        } catch (UnsupportedLookAndFeelException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ImageJPanel imageJPanel1;
    private ImageJPanel imageJPanel2;
    private javax.swing.JButton jButtonTransform;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void myInit() {

        if (imageRezerev.getHeight(null) < jScrollPane1.getMaximumSize().height) {
            if (imageRezerev.getWidth(null) < jScrollPane1.getMaximumSize().width) {
                System.out.println("1");
                jScrollPane1.setSize(new Dimension(imageRezerev.getWidth(null) + 2, imageRezerev.getHeight(null) + 2));
                jScrollPane1.setPreferredSize(new Dimension(imageRezerev.getWidth(null) + 2, imageRezerev.getHeight(null) + 2));

                jScrollPane2.setSize(new Dimension(imageRezerev.getWidth(null) + 2, imageRezerev.getHeight(null) + 2));
                jScrollPane2.setPreferredSize(new Dimension(imageRezerev.getWidth(null) + 2, imageRezerev.getHeight(null) + 2));
            } else {
                System.out.println("2");
                jScrollPane1.setSize(new Dimension(jScrollPane1.getMaximumSize().width, imageRezerev.getHeight(null) + 19));
                jScrollPane1.setPreferredSize(new Dimension(jScrollPane1.getMaximumSize().width, imageRezerev.getHeight(null) + 19));

                jScrollPane2.setSize(new Dimension(jScrollPane2.getMaximumSize().width, imageRezerev.getHeight(null) + 19));
                jScrollPane2.setPreferredSize(new Dimension(jScrollPane2.getMaximumSize().width, imageRezerev.getHeight(null) + 19));
            }

        } else if (imageRezerev.getWidth(null) < jScrollPane1.getMaximumSize().width) {
            System.out.println("3");
            jScrollPane1.setSize(new Dimension((imageRezerev.getWidth(null) + 19), jScrollPane1.getMaximumSize().height));
            jScrollPane1.setPreferredSize(new Dimension((imageRezerev.getWidth(null) + 19), jScrollPane1.getMaximumSize().height));

            jScrollPane2.setSize(new Dimension((imageRezerev.getWidth(null) + 19), jScrollPane2.getMaximumSize().height));
            jScrollPane2.setPreferredSize(new Dimension((imageRezerev.getWidth(null) + 19), jScrollPane2.getMaximumSize().height));
        } else {
            System.out.println("4");
            jScrollPane1.setSize(new Dimension(jScrollPane1.getMaximumSize().width, jScrollPane1.getMaximumSize().height));
            jScrollPane1.setPreferredSize(new Dimension(jScrollPane1.getMaximumSize().width, jScrollPane1.getMaximumSize().height));

            jScrollPane2.setSize(new Dimension(jScrollPane2.getMaximumSize().width, jScrollPane2.getMaximumSize().height));
            jScrollPane2.setPreferredSize(new Dimension(jScrollPane2.getMaximumSize().width, jScrollPane2.getMaximumSize().height));
        }
        pack();
    }

    public void setDefaltPoints(){
        pointsOriginal.add(new Point(10, 5));
        pointsOriginal.add(new Point(400, 15));
        pointsOriginal.add(new Point(200, 530));

        pointsTransform.add(new Point(9, 14));
        pointsTransform.add(new Point(180, 20));
        pointsTransform.add(new Point(95, 200));


        BufferedImage newImage = new BufferedImage(imageRezerev.getWidth(null), imageRezerev.getHeight(null), BufferedImage.TYPE_INT_RGB);
        Graphics gr = newImage.createGraphics();
        gr.drawImage(imageRezerev, 0, 0, null);
        pointsOriginal.Draw(newImage.getGraphics());
        imageJPanel1.setImage(newImage);
        jScrollPane1.updateUI();

        BufferedImage newImage2 = new BufferedImage(d.width, d.height, BufferedImage.TYPE_INT_RGB);
        Graphics gr2 = newImage2.createGraphics();
        gr2.fillRect(0, 0, d.width, d.height);
        pointsTransform.Draw(newImage2.getGraphics());
        imageJPanel2.setImage(newImage2);
        jScrollPane2.updateUI();
    }
}
